name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and build
      run: |
        sudo gem install jekyll
        sudo gem install jekyll-paginate
        jekyll build -d docs -t
    - uses: EndBug/add-and-commit@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
